### ISSUE TITLE
Add a fullscreen button for mail body editor

### ISSUE THREAD

**Issue by piscopancer** [RiskyMH/Email#5]
![image](https://github.com/RiskyMH/EmailThing/assets/109352196/8da87db4-5781-4039-8cd9-a1ec8e090119)

Sometimes I feel like I want to be only focused on the message in the email, similarly to when I open a youtube video fullscreen. If you like this idea, think about adding this feature

**Comment by RiskyMH** [comment]
For now, I don't think this would be a simple task and doesn't seem that worthwhile (the window is already huge and if you want bigger maybe use a different editor or zoom into the page.

In that place you mention, I think I will have text/wysiwyg selector (ie sometimes you just want the good old plain text instead of whatever I'm markdowning.

Thanks for the feature request though, I will try to remember this for if/when I want to revamp again!
